{% set goname = "github.com/rgburke/grv" %}
{% set version = "0.3.2" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-src.tar.gz
    sha256: 988788cce5c581531c26df9048e4187440c5ebc9811afd371d565436dfb65d57
    patches:
      - 0001_cmake_prefix_path.patch

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - make build-only
    - mv "grv" "$PREFIX/bin"        # [unix]
    - mv "grv" "%LIBRARY_BIN%\grv"  # [win]

requirements:
  build:
    - {{ compiler('c') }}           # [unix]
    - {{ compiler('m2w64_c') }}     # [win]
    - {{ compiler('cgo') }}
    - cmake
    - {{posix}}make
    - {{posix}}pkg-config
  host:
    - {{posix}}ncurses
    - readline                      # [unix]
    - {{posix}}libreadline          # [win]
  run:
    - {{posix}}ncurses
    - readline                      # [unix]
    - {{posix}}libreadline          # [win]

test:
  commands:
    - grv -h || true                # [unix]
    - grv -h || exit 0              # [win]

about:
  home: https://{{ goname }}
  license: GPLv3
  license_family: GPL3
  license_file: {{ pkg_src }}/LICENSE
  summary: GRV is a terminal interface for viewing Git repositories
  doc_url: https://{{ goname }}/blob/master/doc/documentation.md
  dev_url: https://{{ goname }}

extra:
  recipe-maintainers:
    - dbast
