{% set name = "protovalidate" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/protovalidate-{{ version }}.tar.gz
  sha256: 12bd7c126fc000c5cbee5bf0f4cd01e0ba0e353f585b0aaa68df03e788939412

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - protobuf
    - cel-python

test:
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Protocol Buffer Validation for Python
  dev_url: https://github.com/bufbuild/protovalidate-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
