{% set version = "3.96" %}

package:
  name: upx
  version: {{ version }}

source:
  url: https://github.com/upx/upx/releases/download/v{{ version }}/upx-{{ version }}-src.tar.xz
  sha256: 47774df5c958f2868ef550fb258b97c73272cb1f44fe776b798e393465993714

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - upx --help

about:
  home: https://upx.github.io/
  license: GPL-2
  license_family: GPL
  license_file: LICENSE
  summary: |
    UPX - the Ultimate Packer for eXecutables
  description: |
    UPX is a free, portable, extendable, high-performance executable
    packer for several executable formats.
  dev_url: https://github.com/upx/upx

extra:
  recipe-maintainers:
    - dbast
